### ISSUE TITLE
Issue with Python3

### ISSUE THREAD

**Issue by ahkarami** [CSAILVision/places365#33]
Hi,
When I run the `run_placesCNN_basic.py` in **Python3** [with PyTorch 0.2] the following error occurred:
`$ python3 run_placesCNN_basic.py`

```
Traceback (most recent call last):
  File "run_placesCNN_basic.py", line 26, in <module>
    model = torch.load(model_weight, map_location=lambda storage, loc: storage) # model trained in GPU could be deployed in CPU machine like this!
  File "/home/karami/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/home/karami/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 379, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 875: ordinal not in range(128)

```
would you please help me to fix this issue.

**Comment by metalbubble** [comment]
Refer to this issue https://github.com/CSAILVision/places365/issues/25
