### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

### ISSUE THREAD

**Issue by oddmen** [CSAILVision/places365#40]
why run the run_placesCNN_unified.py show this error.

Traceback (most recent call last):
  File "/home/xyx/Downloads/places365 new/run_placesCNN_unified.py", line 132, in <module>
    input_img = V(tf(img).unsqueeze(0), volatile=True)
  File "/home/xyx/anaconda2/lib/python2.7/site-packages/torchvision/transforms.py", line 29, in __call__
    img = t(img)
  File "/home/xyx/anaconda2/lib/python2.7/site-packages/torchvision/transforms.py", line 139, in __call__
    ow = int(self.size * w / h)
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

**Comment by metalbubble** [comment]
That's relevant to a compatibility bug in torchvision and the latest torch. You need to upgrade torchvision.
