### ISSUE TITLE
Error when loading pre-trained model in pytorch 0.4

### ISSUE THREAD

**Issue by asheroin** [CSAILVision/places365#46]
I'm using pytorch0.4 with python2.7 and had some problems when loading the pre-trained model. I had change the model download link by delete '_python36' and download the model for python2.7.

The log is below:
`
Traceback (most recent call last):
  File "run_placesCNN_basic.py", line 77, in <module>
    logit = model.forward(input_img)
  File "/home/public/anaconda2/lib/python2.7/site-packages/torchvision/models/resnet.py", line 140, in forward
    x = self.bn1(x)
  File "/home/public/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/public/anaconda2/lib/python2.7/site-packages/torch/nn/modules/batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/public/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'BatchNorm2d' object has no attribute 'track_running_stats'
`

How to solve this problem without downgrade the pytorch?

**Comment by metalbubble** [comment]
fixed. please try again.
