### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'

### ISSUE THREAD

**Issue by zhangmy23** [CSAILVision/places365#49]
Hi all!
while running run_placesCNN_basic.py, this error comes up
Traceback (most recent call last):
  File "run_placesCNN_basic.py", line 31, in <module>
    checkpoint = torch.load(model_file, map_location=lambda storage, loc: storage)
  File "/home/pytorch_py35/lib/python3.5/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/pytorch_py35/lib/python3.5/site-packages/torch/serialization.py", line 412, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.
Any advice? Thanks!

**Comment by metalbubble** [comment]
This [issue](https://github.com/CSAILVision/places365/issues/25) might be helpful

**Comment by Dhanasekar-S** [comment]
_pickle.UnpicklingError: invalid load key, '<'.

The error still persists. Any other solutions?

**Comment by xiaoluojun** [comment]
UnpicklingError: invalid load key, '<'.
Any other solutions?

**Comment by SeungJunnn** [comment]
same here

**Comment by acrobotache** [comment]
pickle.UnpicklingError: invalid load key, '\x0d'.
getting above error

**Comment by ldaumail** [comment]
Any solution found so far?

**Comment by CarolinGao** [comment]
This error may caused by your fragmentary model.

**Comment by swuxyj** [comment]
i solved this problem by re-downloading the model

**Comment by tiandao091** [comment]
> i solved this problem by re-downloading the model

model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=(True)) 
how to re-downloading the model?

**Comment by ANABUR920** [comment]
still cannot fix, any solution found so far? It seems that the PyTorch version issues...

**Comment by jatasya990** [comment]
_pickle.UnpicklingError: invalid load key, '%'.

how to deal with this?

**Comment by niknah** [comment]
Download the ~/.u2net/u2net.pth manually from  https://drive.google.com/file/d/1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ/view?usp=sharing

I have put a fix here https://github.com/danielgatis/rembg/issues/229

**Comment by Oulsjeg** [comment]
Any solution yet to the 'UnpicklingError: invalid load key, '<''?

**Comment by giveloves** [comment]
Check your torch version. I solved this by upgrading my torch to 1.8.2. It is said in README that the version of torch needs to be higher than 1.3.0.

**Comment by Ahmoudahmed** [comment]
_pickle.UnpicklingError: invalid load key, '\x19'.
