### ISSUE TITLE
AttributeError: 'module' object has no attribute 'constant_'

### ISSUE THREAD

**Issue by chenliqiong** [CSAILVision/places365#51]
Hello，everyone！ Running run_placesCNN_unified.py in this repository I run into this following error:

Traceback (most recent call last):
  File "run_placesCNN_unified.py", line 124, in <module>
    model = load_model()
  File "run_placesCNN_unified.py", line 94, in load_model
    model = wideresnet.resnet18(num_classes=365)
  File "/home/user/zou/code/places365/wideresnet.py", line 164, in resnet18
    model = ResNet(BasicBlock, [2, 2, 2, 2], **kwargs)
  File "/home/user/zou/code/places365/wideresnet.py", line 120, in __init__
    nn.init.constant_(m.weight, 1)
AttributeError: 'module' object has no attribute 'constant_'

Any advice about that? Thanks in advance!

**Comment by chenliqiong** [comment]
I solved this by change 'constant_' to 'constant'.
Thanks for the author's great work.
