### ISSUE TITLE
running in windows cmd platform

### ISSUE THREAD

**Issue by tyriong** [CSAILVision/places365#86]
Hi, I'm quite new to this field so i'm still learning while working.

i tried running the basic code script and encounter this error;

'wget' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "run_placesCNN_basic.py", line 24, in <module>
    checkpoint = torch.load(model_file, map_location=lambda storage, loc: storage)
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'resnet18_places365.pth.tar'

I figure it might be related to prerequisites installation as there is files missing. however most of the manual are guide for Ubuntu OS and OS X. Is there any way or guide to use on Windows Command prompt platform?

**Comment by zhangzhe623** [comment]
I also have this problem
